# Generated by Django 3.2.7 on 2021-10-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='topic',
            new_name='customer_need',
        ),
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(default='car', max_length=100),
            preserve_default=False,
        ),
    ]
