# Generated by Django 3.2.7 on 2021-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211021_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
