# Generated by Django 3.2.7 on 2021-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_need',
            field=models.CharField(choices=[('interested', "I'm interested in this"), ('test drive', "I'd like to test drive this"), ('best price', "I'd like to know your best price for this"), ('history report', "I'd like a history report for this")], max_length=250, verbose_name='Topic'),
        ),
    ]
