# Generated by Django 3.2.7 on 2021-10-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitterlink', models.URLField(max_length=100)),
                ('create_dta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
