# Generated by Django 3.2.7 on 2021-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211007_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='Cars/%d-%m-%Y/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], help_text='Enter the number of passengers', verbose_name='number of passengers'),
        ),
        migrations.AlterField(
            model_name='car',
            name='views_images_1',
            field=models.ImageField(blank=True, upload_to='Cars/%d-%m-%Y/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='views_images_2',
            field=models.ImageField(blank=True, upload_to='Cars/%d-%m-%Y/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='views_images_3',
            field=models.ImageField(blank=True, upload_to='Cars/%d-%m-%Y/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='views_images_4',
            field=models.ImageField(blank=True, upload_to='Cars/%d-%m-%Y/'),
        ),
    ]
