# Generated by Django 3.2.7 on 2021-10-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20211007_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='availibility',
        ),
    ]
