# Generated by Django 3.2.7 on 2021-10-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_available_car_availibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='availibility',
            field=models.CharField(choices=[('Rent', 'For Rent'), ('Sale', 'For Sale'), ('Not available', 'Not available')], max_length=100, verbose_name='availibility'),
        ),
    ]
